stages:
  - tests
  - docs
  - deploy

# running all the python tests
python_tests:
  stage: tests
  image: python:3.6.5-alpine
  script:
    - apk --no-cache add git
    - apk --no-cache add bash
    - pip install -r requirements.txt
    - python setup.py test
  artifacts:
    paths:
      - cover/*
    expire_in: 1 week


# building all the python docs as html
python_docs:
  stage: docs
  image: python:3.6.5-alpine
  script:
    - apk --no-cache add make
    - apk --no-cache add git
    - pip install sphinx sphinx_rtd_theme requests
    - pip install -r requirements.txt
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html/*
    expire_in: 1 week
  only: [master, tags]

pages:
  stage: deploy
  script:
    - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
