# building all the documents for the dissertation
docs-dissertation:
  image: aergus/latex
  script:
    - cd dissertation
    - latexmk -pdf -shell-escape
  artifacts:
    paths:
      - dissertation/*.pdf
    expire_in: 1 week
  only: [dissertation]
