#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from sciit import IssueRepo, IssueListInCommit
from sciit.cli.color import CPrint
from sciit.errors import RepoObjectDoesNotExistError
import colorama

colorama.init()
repo = IssueRepo()

if not repo.is_init():
    CPrint.bold_red('error: Issue Repository not setup')
    print('Solve error by building issue repository using: git sciit init')
    exit(127)

repo.sync()
try:
    issue_commit = IssueListInCommit(repo, repo.head.commit.binsha)
except RepoObjectDoesNotExistError as error:
    CPrint.bold_red(error)
    print('Solve error by rebuilding issue repository using: git sciit init -r')
    exit(127)

# dealing with a detached head
try:
    location = repo.head.ref.name
except TypeError:
    location = 'DETACHED:' + repo.head.commit.hexsha


# show issue status at head to the user
if issue_commit.open_issues > 0:
    result = str(issue_commit.open_issues) + ' Open Issues @' + location
    CPrint.bold_red(result)
else:
    result = 'No Open Issues @' + location
    CPrint.bold_green(result)
