#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Script that contains the operation to be done
 after a merge is made. This script builds the 
 issues from the latest commit to the last issue and
 stores it in our issue repository

:@author: Nystrom Edwards
:Created: 23 July 2018
"""
from sciit import IssueRepo, IssueCommit
from termcolor import colored
import colorama

colorama.init()
repo = IssueRepo()
repo.sync()
icommit = IssueCommit(repo, repo.head.commit.binsha)

# show issue status at head to the user
if icommit.open_issues > 0:
    result = str(icommit.open_issues) + \
        ' Open Issues @' + repo.active_branch.name
    print(colored(result, 'red', attrs=['bold']))
else:
    result = 'No Open Issues @' + repo.active_branch.name
    print(colored(result, 'green', attrs=['bold']))
